### ISSUE TITLE
importlib.resources does not work when installing with apt

### ISSUE THREAD

**Issue by nrueh** [potassco/plingo#13]
When installing plingo with apt on Ubuntu, it is using the system python 3.8 version which does not have `importlib.resources.file`. This gives an error for `--frontend=plog`.
I had added the following two lines when we put everything in the `plingo` folder for pip packaging. This import the `meta.lp` file which needs to be added for P-log.
```
from importlib.resources import files as importfiles
meta_path = importfiles('plingo').joinpath('meta.lp')
```
@rkaminsk Do you have an idea how to fix this? Do we even need the `importlib` library?

```
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/clingo/application.py", line 293, in _pyclingo_application_main      
    app.main(Control(control), [ _to_str(files[i]) for i in range(size) ]) 
File "/usr/lib/python3/dist-packages/plingo/plingo_app.py", line 291, in main 
    obs = self._preprocessing(ctl, files) 
File "/usr/lib/python3/dist-packages/plingo/plingo_app.py", line 205, in _preprocessing 
    from importlib.resources import files as importfiles 
ImportError: cannot import name 'files' from 'importlib.resources' (/usr/lib/python3.8/importlib/resources.py) 
*** ERROR: (plingo): no message UNKNOWN`
```

**Comment by rkaminsk** [comment]
You could just put the file as a string in the python source code.

**Comment by rkaminsk** [comment]
I had a look at the [documentation](https://importlib-resources.readthedocs.io/en/latest/migration.html). If there were a lot of resources that had to be loaded, I would conditionally import the `pkg_resources` package. With just one or two encodings this is not worth the effort, though. I'ld just use
```python
encoding = '''
...
...
...
'''
```

**Comment by nrueh** [comment]
That sounds good to me. I will implement it
